### ISSUE TITLE
can't encounter path to model

### ISSUE THREAD

**Issue by i-am-charlie** [tryolabs/TLSphinx#10]
Buenos Dias Bruno,

Sabes que no puedo acceder al model usando el código de LiveDecoder en los tests.  Usando lo siguiente:

func getModelPath() -> String? {
            return NSBundle(forClass: LiveDecode.self).pathForResource("en-us", ofType: nil)
        }
if let modelPath = getModelPath() {
        } else {
            print("Can't access pocketsphinx model. Bundle root: \(NSBundle.mainBundle())")
        }

Y me devuelve:

Can't access pocketsphinx model. Bundle root: NSBundle </var/mobile/Containers/Bundle/Application/5106B682-3E94-4632-A3CC-6436F6F8DB28/hello_v1.app>

No tengo mucha experiencia con ni swift ni Xcode, y parece que los archivos (del modelo) existen en el directorio del Carthage en mi laptop y el app no los puede reconocer o encontrar.

Deberia yo poner los archivos en otro lado... o como senalo en swift donde existen, porque el getModelPath() no me resulta.  Esto resulta en el Simulator igual que en mi celular.

**Comment by i-am-charlie** [comment]
Ya lo hice!

Instead of having the directory "model" be the "root" of the files... I simply removed it and made "en-us" the "root" (the files added to the app)

**Comment by BrunoBerisso** [comment]
Glad to know you fix it yourself! :) Congrats!

Please consider pick one human language (preferible english) when writing public stuff. :+1: 

Good luck!
