### ISSUE TITLE
Live Decoding issue

### ISSUE THREAD

**Issue by danigoland** [tryolabs/TLSphinx#11]
When calling startDecodingSpeech, I get no hypothesis back what so ever,
When I looked in the temp directory , it is indeed recording the files.
Looks like it is stuck at  audioFileHandle.readabilityHandler = { (handler: NSFileHandle) -> Void in .

Was anyone able to get the live decoding to work?

Thanks for your help

**Comment by i-am-charlie** [comment]
I had and am still having the exact same issue.  #upvote

**Comment by gavi** [comment]
Same issue here. Did anyone get this working? I am trying on iOS 9.3, Xcode 7.3 - iPad Pro

**Comment by GojaN** [comment]
Hi

I will try to fix this. I'm using the decode method with success.

I think the implementation for live decode is not the right one so I expect to write it again.

Keep you updated

**Comment by maurodec** [comment]
@danigoland, @i-am-charlie , @gavi Can any of you guys provide an example so we can reproduce this issue?

**Comment by BrunoBerisso** [comment]
Close now because it's to quiet. If someone have an example we can reopen it.
Thanks!
