### ISSUE TITLE
TLSphinx for Mac Apps

### ISSUE THREAD

**Issue by melbek** [tryolabs/TLSphinx#13]
I'm currently working on getting TLSphinx working for Mac Apps.
I know that "Speech from Mic" won't work because of missing AVFoundation Classes, but a working "Speech from File" would be sufficient.

But the main problem is, that the sphinx static libraries are build for iOS.
After adding a new target and configuring everything, I get this warning:

ld: warning: URGENT: building for OSX, but linking in object file (PATHTOTLSPHINX/TLSphinx/Sphinx/lib/sphinxbase/x86_64/libsphinxbase.a(cmd_ln.o)) built for iOS. Note: This will be an error in the future.

I still can successfully build a Mac App and run the sphinx test file tough.
There are many static libraries in the Sphinx directory. Is there a version also for mac? Maybe the one in "x86_64" folder?

Thank you in advance.

**Comment by BrunoBerisso** [comment]
Hi, thanks for your interest in TLSphinx!

You are in the right path about how integrate TLSphinx. The warning you are seeing is because I build all the architectures for iOS, even the ones that aren't ARM for work on the simulator. The .a files at the root of the `lib`s subfolders are _fat libraries_ that contain all the other architecture specific libraries inside. 

[Here](https://github.com/tryolabs/TLSphinx/files/213131/build.scripts.zip) are two scripts I use to build both libraries: Pocketsphinx and Sphinxbase for iOS. The scripts are almost identical, just a few lines differ. For build the library for OSX I think you just need to remove all the references to `iOS` SDK and such.

[This](http://cmusphinx.sourceforge.net/wiki/tutorialpocketsphinx) is the oficial installation guid. This will output a C library that wont work _as is_ in Swift, you will need to wrap it in a module. There are many tutorials on the web about that, it's really easy.

Please follow one of this paths and let us know which one work best for you.

**Comment by cocoBavan** [comment]
Will anyone be kind enough to update this project for mac as well? Steps look very daunting for a newbie. :(

**Comment by ss-pq** [comment]
Perhaps this helps:
http://www.moreiscode.com/getting-started-with-cmu-sphinx-on-mac-os-x/

**Comment by ss-pq** [comment]
Note that building on Yosemite requires some brew components that need special attention to be installed. Something that became clear after a day of messing about. : )

**Comment by cocoBavan** [comment]
But, that will enable you to run the pocket sphinx in your mac. If I want to ship it with my mac app, the how will this be possible? I need to get a static library or framework by building it right? Pocketsphinx people have [https://github.com/cmusphinx/pocketsphinx-ios-demo](url) for iOS. I thought it will be just a case of modifying the script to work for MacOS. My limited knowledge in the compiler->linker phase is not  helping me to so.

**Comment by ss-pq** [comment]
The script as @BrunoBerisso mentioned is to build the libraries for OS X, which the shared link does, then its quite easy to write a wrapper for the desired functionalities for the libraries.

**Comment by cocoBavan** [comment]
Thank you ss-pq. Anyway, I managed to achieve what I wanted after convincing myself that this is not as scary as it looks. I have shared the script and steps [here](https://github.com/cocoBavan/TLSphinxMac/).

**Comment by ss-pq** [comment]
Awesome! : )

**Comment by ss-pq** [comment]
Although it would be interesting to implement a microphone feed rather than a file read analysis. Have you by any chance found a solution for that @cocoBavan ?!

**Comment by ss-pq** [comment]
This as the original smusphinx-continious bin implementation uses the carbon manager, and is going to be deprecated, and the file is somehow clumsy.

**Comment by ss-pq** [comment]
There are plenty of open framework solution, but swift would be amazing....

**Comment by ss-pq** [comment]
Somehow the TLSphinx eats more than hundreds MB of memory on OS X, while perhaps this implementation serves the purpose for realtime feed in Swift with a lot less overhead.
https://github.com/ss-pq/SphinxMac.git

**Comment by ss-pq** [comment]
Hi Guys...
Was testing the Mac version of the wrapper while testing, and it seems that the wrapper leaks. 
Although implemented a record file release between utterances, as the current file handler does not seem to work on the mac version, and yet it accumulates some junk.

**Comment by ss-pq** [comment]
And there it is: Streaming audio version for Mac inspired by TLS! 
Thank you!
https://github.com/ss-pq/SSPhinx

**Comment by BrunoBerisso** [comment]
Great! @ss-pq  Does the `startDecodingSpeech` logic work on iOS? The current implementation is more like a place-holder than a final solution :(

**Comment by ss-pq** [comment]
Since you asked, did some testing, and indeed, the implementation method of streaming does work on iOS as well, although the streaming seems to create more of a memory overhead than reading from file, but both versions on the implementation seems to be stable without leaks. : )

**Comment by BrunoBerisso** [comment]
That's great!

I don't really know if the current implementation with the file handler is
the right way or a hack 😕

I believe your implementation is the right way to do it. Hope some day I
have the time to improve TLSphinx. And maybe write a wrapper around Sphinx
with the new Swift 3 C APIs facilities 😊

Thanks for checking this out on iOS!

**Comment by ss-pq** [comment]
Made a pull request with the streaming implementation, until 3.0 it. : )

**Comment by ss-pq** [comment]
a new project I'm working on implementing the streamer.

http://www.mainvolume.com/8Ø8/

preview link:
https://www.dropbox.com/s/9136f2d5um1lx0d/8%C3%988%E2%84%A2.pkg?dl=0

Let me know what you think

**Comment by brntphish** [comment]
ss-pq

Thanks for the mac version of this all flashed out. Any change you have also built the training ability into a framwork that is mac/swift compatible?

**Comment by ss-pq** [comment]
@brntphish : )

The training program has not been build yet as the project did not demand such modules, but perhaps when refactoring for swift 3.0, then it can also be implemented. 

Here is the first released version on AppStore containing the refactored TLSphinx module for Mac:

https://itunes.apple.com/gb/app/tm/id1131099213?mt=12

**Comment by BrunoBerisso** [comment]
Thanks @ss-pq for your PR about this and congratulations for your app! It's really amazing and fun :D I already merge a trimmed version of your work to TLSphinx.

Will close this issue now.
