### ISSUE TITLE
File not found with angled..

### ISSUE THREAD

**Issue by terenzeyuen** [tryolabs/TLSphinx#17]
Hi I am getting the following errors using Carthage..any help?

<img width="897" alt="screen shot 2016-07-14 at 18 21 15" src="https://cloud.githubusercontent.com/assets/2553680/16848895/da2a9530-49ef-11e6-9d5c-c1b228fd3069.png">

**Comment by terenzeyuen** [comment]
Fixed.

**Comment by BrunoBerisso** [comment]
Thanks!
