### ISSUE TITLE
Reading local file

### ISSUE THREAD

**Issue by terenzeyuen** [tryolabs/TLSphinx#18]
Can't seem to read local file..

```
let audioFile = NSBundle.mainBundle().URLForResource("test", withExtension: "m4a")
                    
                    decoder.decodeSpeechAtPath(String(audioFile)) {
                        
                        if let hyp: Hypotesis = $0 {
                            // Print the decoder text and score
                            print("Text: \(hyp.text) - Score: \(hyp.score)")
                        } else {
                            // Can't decode any speech because of an error
                            print("Error:")
                        }
                }
```

**Comment by terenzeyuen** [comment]
That is when I use reference, if I copy the en-us folder as group I get:

Reading plist: The data couldn't be read...

<img width="299" alt="screen shot 2016-07-14 at 19 04 07" src="https://cloud.githubusercontent.com/assets/2553680/16850173/d5044c08-49f5-11e6-91ed-38c70bf04fb7.png">

Anything I am doing wrongly?

**Comment by maurodec** [comment]
Hey @terenzeyuen. Check out [this](https://github.com/tryolabs/TLSphinx/blob/master/TLSphinxTests/Basic.swift#L58) unit test. It's doing the same thing you're trying to do here. the problem seems to be that you did not install TLSphinx correctly. Make sure you followed the [installation](https://github.com/tryolabs/TLSphinx#installation) steps correctly.

**Comment by terenzeyuen** [comment]
Thanks @maurodec – checked a few times but I dont' see anything on installation though. I can run and compile it but it just doesnt read the audio file. Does it support m4a? My runtime log if anyone can point me in the right direection please.

INFO: cmd_ln.c(697): Parsing command line:
\
	-hmm /var/containers/Bundle/Application/8C249C4B-0F90-470D-A065-EE8284AB8008/SphinxDWR.app/en-us/en-us \
	-lm /var/containers/Bundle/Application/8C249C4B-0F90-470D-A065-EE8284AB8008/SphinxDWR.app/en-us/en-us.lm.dmp \
	-dict /var/containers/Bundle/Application/8C249C4B-0F90-470D-A065-EE8284AB8008/SphinxDWR.app/en-us/cmudict-en-us.dict 

Current configuration:
[NAME]		[DEFLT]		[VALUE]
-agc		none		none
-agcthresh	2.0		2.000000e+00
-allphone			
-allphone_ci	no		no
-alpha		0.97		9.700000e-01
-ascale		20.0		2.000000e+01
-aw		1		1
-backtrace	no		no
-beam		1e-48		1.000000e-48
-bestpath	yes		yes
-bestpathlw	9.5		9.500000e+00
-ceplen		13		13
-cmn		current		current
-cmninit	8.0		8.0
-compallsen	no		no
-debug				0
-dict				/var/containers/Bundle/Application/8C249C4B-0F90-470D-A065-EE8284AB8008/SphinxDWR.app/en-us/cmudict-en-us.dict
-dictcase	no		no
-dither		no		no
-doublebw	no		no
-ds		1		1
-fdict				
-feat		1s_c_d_dd	1s_c_d_dd
-featparams			
-fillprob	1e-8		1.000000e-08
-frate		100		100
-fsg				
-fsgusealtpron	yes		yes
-fsgusefiller	yes		yes
-fwdflat	yes		yes
-fwdflatbeam	1e-64		1.000000e-64
-fwdflatefwid	4		4
-fwdflatlw	8.5		8.500000e+00
-fwdflatsfwin	25		25
-fwdflatwbeam	7e-29		7.000000e-29
-fwdtree	yes		yes
-hmm				/var/containers/Bundle/Application/8C249C4B-0F90-470D-A065-EE8284AB8008/SphinxDWR.app/en-us/en-us
-input_endian	little		little
-jsgf				
-keyphrase			
-kws				
-kws_plp	1e-1		1.000000e-01
-kws_threshold	1		1.000000e+00
-latsize	5000		5000
-lda				
-ldadim		0		0
-lifter		0		0
-lm				/var/containers/Bundle/Application/8C249C4B-0F90-470D-A065-EE8284AB8008/SphinxDWR.app/en-us/en-us.lm.dmp
-lmctl				
-lmname				
-logbase	1.0001		1.000100e+00
-logfn				
-logspec	no		no
-lowerf		133.33334	1.333333e+02
-lpbeam		1e-40		1.000000e-40
-lponlybeam	7e-29		7.000000e-29
-lw		6.5		6.500000e+00
-maxhmmpf	30000		30000
-maxwpf		-1		-1
-mdef				
-mean				
-mfclogdir			
-min_endfr	0		0
-mixw				
-mixwfloor	0.0000001	1.000000e-07
-mllr				
-mmap		yes		yes
-ncep		13		13
-nfft		512		512
-nfilt		40		40
-nwpen		1.0		1.000000e+00
-pbeam		1e-48		1.000000e-48
-pip		1.0		1.000000e+00
-pl_beam	1e-10		1.000000e-10
-pl_pbeam	1e-10		1.000000e-10
-pl_pip		1.0		1.000000e+00
-pl_weight	3.0		3.000000e+00
-pl_window	5		5
-rawlogdir			
-remove_dc	no		no
-remove_noise	yes		yes
-remove_silence	yes		yes
-round_filters	yes		yes
-samprate	16000		1.600000e+04
-seed		-1		-1
-sendump			
-senlogdir			
-senmgau			
-silprob	0.005		5.000000e-03
-smoothspec	no		no
-svspec				
-tmat				
-tmatfloor	0.0001		1.000000e-04
-topn		4		4
-topn_beam	0		0
-toprule			
-transform	legacy		legacy
-unit_area	yes		yes
-upperf		6855.4976	6.855498e+03
-uw		1.0		1.000000e+00
-vad_postspeech	50		50
-vad_prespeech	10		10
-vad_threshold	2.0		2.000000e+00
-var				
-varfloor	0.0001		1.000000e-04
-varnorm	no		no
-verbose	no		no
-warp_params			
-warp_type	inverse_linear	inverse_linear
-wbeam		7e-29		7.000000e-29
-wip		0.65		6.500000e-01
-wlen		0.025625	2.562500e-02

INFO: cmd_ln.c(697): Parsing command line:
\
	-lowerf 130 \
	-upperf 6800 \
	-nfilt 25 \
	-transform dct \
	-lifter 22 \
	-feat 1s_c_d_dd \
	-svspec 0-12/13-25/26-38 \
	-agc none \
	-cmn current \
	-varnorm no \
	-model ptm \
	-cmninit 40,3,-1 

Current configuration:
[NAME]		[DEFLT]		[VALUE]
-agc		none		none
-agcthresh	2.0		2.000000e+00
-alpha		0.97		9.700000e-01
-ceplen		13		13
-cmn		current		current
-cmninit	8.0		40,3,-1
-dither		no		no
-doublebw	no		no
-feat		1s_c_d_dd	1s_c_d_dd
-frate		100		100
-input_endian	little		little
-lda				
-ldadim		0		0
-lifter		0		22
-logspec	no		no
-lowerf		133.33334	1.300000e+02
-ncep		13		13
-nfft		512		512
-nfilt		40		25
-remove_dc	no		no
-remove_noise	yes		yes
-remove_silence	yes		yes
-round_filters	yes		yes
-samprate	16000		1.600000e+04
-seed		-1		-1
-smoothspec	no		no
-svspec				0-12/13-25/26-38
-transform	legacy		dct
-unit_area	yes		yes
-upperf		6855.4976	6.800000e+03
-vad_postspeech	50		50
-vad_prespeech	10		10
-vad_threshold	2.0		2.000000e+00
-varnorm	no		no
-verbose	no		no
-warp_params			
-warp_type	inverse_linear	inverse_linear
-wlen		0.025625	2.562500e-02

INFO: acmod.c(252): Parsed model-specific feature parameters from /var/containers/Bundle/Application/8C249C4B-0F90-470D-A065-EE8284AB8008/SphinxDWR.app/en-us/en-us/feat.params
INFO: feat.c(715): Initializing feature stream to type: '1s_c_d_dd', ceplen=13, CMN='current', VARNORM='no', AGC='none'
INFO: cmn.c(143): mean[0]= 12.00, mean[1..12]= 0.0
INFO: acmod.c(171): Using subvector specification 0-12/13-25/26-38
INFO: mdef.c(518): Reading model definition: /var/containers/Bundle/Application/8C249C4B-0F90-470D-A065-EE8284AB8008/SphinxDWR.app/en-us/en-us/mdef
INFO: mdef.c(531): Found byte-order mark BMDF, assuming this is a binary mdef file
INFO: bin_mdef.c(336): Reading binary model definition: /var/containers/Bundle/Application/8C249C4B-0F90-470D-A065-EE8284AB8008/SphinxDWR.app/en-us/en-us/mdef
INFO: bin_mdef.c(516): 42 CI-phone, 137053 CD-phone, 3 emitstate/phone, 126 CI-sen, 5126 Sen, 29324 Sen-Seq
INFO: tmat.c(206): Reading HMM transition probability matrices: /var/containers/Bundle/Application/8C249C4B-0F90-470D-A065-EE8284AB8008/SphinxDWR.app/en-us/en-us/transition_matrices
INFO: acmod.c(124): Attempting to use PTM computation module
INFO: ms_gauden.c(198): Reading mixture gaussian parameter: /var/containers/Bundle/Application/8C249C4B-0F90-470D-A065-EE8284AB8008/SphinxDWR.app/en-us/en-us/means
INFO: ms_gauden.c(292): 42 codebook, 3 feature, size: 
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(198): Reading mixture gaussian parameter: /var/containers/Bundle/Application/8C249C4B-0F90-470D-A065-EE8284AB8008/SphinxDWR.app/en-us/en-us/variances
INFO: ms_gauden.c(292): 42 codebook, 3 feature, size: 
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(294):  128x13
INFO: ms_gauden.c(354): 222 variance values floored
INFO: ptm_mgau.c(476): Loading senones from dump file /var/containers/Bundle/Application/8C249C4B-0F90-470D-A065-EE8284AB8008/SphinxDWR.app/en-us/en-us/sendump
INFO: ptm_mgau.c(500): BEGIN FILE FORMAT DESCRIPTION
INFO: ptm_mgau.c(563): Rows: 128, Columns: 5126
INFO: ptm_mgau.c(595): Using memory-mapped I/O for senones
INFO: ptm_mgau.c(835): Maximum top-N: 4
INFO: phone_loop_search.c(115): State beam -225 Phone exit beam -225 Insertion penalty 0
INFO: dict.c(320): Allocating 137526 * 32 bytes (4297 KiB) for word entries
INFO: dict.c(333): Reading main dictionary: /var/containers/Bundle/Application/8C249C4B-0F90-470D-A065-EE8284AB8008/SphinxDWR.app/en-us/cmudict-en-us.dict
INFO: dict.c(213): Allocated 1007 KiB for strings, 1662 KiB for phones
INFO: dict.c(336): 133425 words read
INFO: dict.c(342): Reading filler dictionary: /var/containers/Bundle/Application/8C249C4B-0F90-470D-A065-EE8284AB8008/SphinxDWR.app/en-us/en-us/noisedict
INFO: dict.c(213): Allocated 0 KiB for strings, 0 KiB for phones
INFO: dict.c(345): 5 words read
INFO: dict2pid.c(396): Building PID tables for dictionary
INFO: dict2pid.c(406): Allocating 42^3 * 2 bytes (144 KiB) for word-initial triphones
INFO: dict2pid.c(132): Allocated 42672 bytes (41 KiB) for word-final triphones
INFO: dict2pid.c(196): Allocated 42672 bytes (41 KiB) for single-phone word triphones
INFO: ngram_model_arpa.c(77): No \data\ mark in LM file
INFO: ngram_model_dmp.c(142): Will use memory-mapped I/O for LM file
INFO: ngram_model_dmp.c(196): ngrams 1=19794, 2=1377200, 3=3178194
INFO: ngram_model_dmp.c(242):    19794 = LM.unigrams(+trailer) read
INFO: ngram_model_dmp.c(288):  1377200 = LM.bigrams(+trailer) read
INFO: ngram_model_dmp.c(314):  3178194 = LM.trigrams read
INFO: ngram_model_dmp.c(339):    57155 = LM.prob2 entries read
INFO: ngram_model_dmp.c(359):    10935 = LM.bo_wt2 entries read
INFO: ngram_model_dmp.c(379):    34843 = LM.prob3 entries read
INFO: ngram_model_dmp.c(407):     2690 = LM.tseg_base entries read
INFO: ngram_model_dmp.c(463):    19794 = ascii word strings read
INFO: ngram_search_fwdtree.c(99): 788 unique initial diphones
INFO: ngram_search_fwdtree.c(148): 0 root, 0 non-root channels, 56 single-phone words
INFO: ngram_search_fwdtree.c(186): Creating search tree
INFO: ngram_search_fwdtree.c(192): before: 0 root, 0 non-root channels, 56 single-phone words
INFO: ngram_search_fwdtree.c(326): after: max nonroot chan increased to 44782
INFO: ngram_search_fwdtree.c(339): after: 573 root, 44654 non-root channels, 47 single-phone words
INFO: ngram_search_fwdflat.c(157): fwdflat: min_ef_width = 4, max_sf_win = 25
INFO: ngram_search_fwdtree.c(432): TOTAL fwdtree 0.00 CPU nan xRT
INFO: ngram_search_fwdtree.c(435): TOTAL fwdtree 0.00 wall nan xRT
INFO: ngram_search_fwdflat.c(176): TOTAL fwdflat 0.00 CPU nan xRT
INFO: ngram_search_fwdflat.c(179): TOTAL fwdflat 0.00 wall nan xRT
INFO: ngram_search.c(303): TOTAL bestpath 0.00 CPU nan xRT
INFO: ngram_search.c(306): TOTAL bestpath 0.00 wall nan xRT
Error:

**Comment by terenzeyuen** [comment]
@maurodec Ok I delete derived data and it seems to compile without errors now. But getting nothing being printed out either – any way I can debug? I installed using Carthage and headers all set correctly.

I have tried:
- Removing test.m4a file from target, getting error as expected
- Removing en-us etc from target, getting error as expected

Tried Live record and file but nothing is being printed...

**Comment by terenzeyuen** [comment]
Code for livedecode – it did asked for Mic access which I have allowed (checked under settings too):

decoder.startDecodingSpeech {
                    
                    if let hyp: Hypotesis = $0 {
                        print(hyp)
                    } else {
                        print("error")
                        // Can't decode any speech because an error
                    }
                }

**Comment by terenzeyuen** [comment]
I think it is reading something...this is what I get but it doesn't print anything out

Code:
 ```
let audioFile  = (modelPath! as NSString).stringByAppendingPathComponent("test.m4a")
                    print(audioFile)
                
                    decoder.decodeSpeechAtPath(String(audioFile)) {
                        
                        if let hyp: Hypotesis = $0 {
                            // Print the decoder text and score
                            print("Text: \(hyp.text) - Score: \(hyp.score)")
                        } else {
                            // Can't decode any speech because of an error
                          //  print("Error:")
                        }
                }
```

Any help? Log below.

/var/containers/Bundle/Application/95F5E512-7037-4C26-9716-1F78CF241F0C/SphinxDWR.app/en-us/test.m4a
INFO: cmn_prior.c(131): cmn_prior_update: from < 40.00  3.00 -1.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00 >
INFO: cmn_prior.c(149): cmn_prior_update: to   < 81.40 -24.99 -3.53 -7.49 -17.06  4.45 -5.20  5.96  5.75 -2.35  1.22 -3.00 -1.89 >
INFO: ngram_search_fwdtree.c(1553):      460 words recognized (9/fr)
INFO: ngram_search_fwdtree.c(1555):   179701 senones evaluated (3328/fr)
INFO: ngram_search_fwdtree.c(1559):   341096 channels searched (6316/fr), 28650 1st, 20749 last
INFO: ngram_search_fwdtree.c(1562):     1992 words for which last channels evaluated (36/fr)
INFO: ngram_search_fwdtree.c(1564):    22861 candidate words for entering last phone (423/fr)
INFO: ngram_search_fwdtree.c(1567): fwdtree 3.48 CPU 6.437 xRT
INFO: ngram_search_fwdtree.c(1570): fwdtree 3.71 wall 6.863 xRT
INFO: ngram_search_fwdflat.c(302): Utterance vocabulary contains 7 words
INFO: ngram_search_fwdflat.c(945):      213 words recognized (4/fr)
INFO: ngram_search_fwdflat.c(947):     9036 senones evaluated (167/fr)
INFO: ngram_search_fwdflat.c(949):     5034 channels searched (93/fr)
INFO: ngram_search_fwdflat.c(951):      489 words searched (9/fr)
INFO: ngram_search_fwdflat.c(954):      232 word transitions (4/fr)
INFO: ngram_search_fwdflat.c(957): fwdflat 0.01 CPU 0.016 xRT
INFO: ngram_search_fwdflat.c(960): fwdflat 0.01 wall 0.021 xRT
INFO: ngram_search.c(1199): </s> not found in last frame, using <s>.52 instead
INFO: ngram_search.c(1252): lattice start node <s>.0 end node <s>.0
INFO: ngram_search.c(1278): Eliminated 97 nodes before end node
INFO: ngram_search.c(1383): Lattice has 98 nodes, 0 links
INFO: ps_lattice.c(1380): Bestpath score: -2147483648
INFO: ps_lattice.c(1384): Normalizer P(O) = alpha(<s>:0:52) = -536899456
INFO: ngram_search_fwdtree.c(432): TOTAL fwdtree 3.48 CPU 6.558 xRT
INFO: ngram_search_fwdtree.c(435): TOTAL fwdtree 3.71 wall 6.992 xRT
INFO: ngram_search_fwdflat.c(176): TOTAL fwdflat 0.01 CPU 0.016 xRT
INFO: ngram_search_fwdflat.c(179): TOTAL fwdflat 0.01 wall 0.021 xRT
INFO: ngram_search.c(303): TOTAL bestpath 0.00 CPU 0.000 xRT
INFO: ngram_search.c(306): TOTAL bestpath 0.00 wall 0.000 xRT

**Comment by BrunoBerisso** [comment]
I did test with the [Pocketsphinx audio files](https://github.com/cmusphinx/pocketsphinx/blob/master/test/data/goforward.raw) and work as expected. I don't think it will work with any audio format different than raw PCM.

Keep in mind that If try to detect arbitrary speech you will get bad results. Sphinx, and TLSphinx, are meant to be use for command like interaction.

Having say that, you should get something when running the live decoding with your mic. Do you try with something like [this](https://github.com/tryolabs/TLSphinx/blob/master/TLSphinxTests/LiveDecode.swift#L20) ?

**Comment by terenzeyuen** [comment]
@BrunoBerisso yes I've tried changing my code to LiveDecoding, given access to Microphone and double checked Settings but nothing gets printed....

My code (including viewdidload):
```

override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        let modelPath = NSBundle.mainBundle().pathForResource("en-us", ofType: nil)
        let hmm = (modelPath! as NSString).stringByAppendingPathComponent("en-us")
        let lm = (modelPath! as NSString).stringByAppendingPathComponent("en-us.lm.dmp")
        let dict = (modelPath! as NSString).stringByAppendingPathComponent("cmudict-en-us.dict")

        if let config = Config(args: ("-hmm", hmm), ("-lm", lm), ("-dict", dict)) {
            if let decoder = Decoder(config:config) {
                decoder.startDecodingSpeech { (hyp) -> () in
                    print("Utterance: \(hyp)")
                }
            } else {
                // Handle Decoder() fail
            }
        } else {
            // Handle Config() fail  
        }

    }
```

**Comment by BrunoBerisso** [comment]
You need to store the decoder in some persistent location because it's get release at the end of `viewDidLoad` and that cancel the operation.

Try create a property in your controller for the decoder. Also we have reports that the live decode process is not working properly, [this pull request](https://github.com/tryolabs/TLSphinx/pull/15) is meant to improve it.

**Comment by terenzeyuen** [comment]
@BrunoBerisso thanks – I tried with an example wav file and it works. So must be my m4a file. :)
http://www.voiptroubleshooter.com/open_speech/american.html

<img width="888" alt="screen shot 2016-07-14 at 21 04 44" src="https://cloud.githubusercontent.com/assets/2553680/16853946/a2ee298a-4a06-11e6-9933-f67d4b48c638.png">

I see, let me try live decoding in other location.

**Comment by terenzeyuen** [comment]
@BrunoBerisso Hmm no luck on live decoding. Nothing gets printed. Anything I am doing wrongly?

Triggering from a button action instead.

```
if let modelPath = getModelPath() {
            
            let hmm = (modelPath as NSString).stringByAppendingPathComponent("en-us")
            let lm = (modelPath as NSString).stringByAppendingPathComponent("en-us.lm.dmp")
            let dict = (modelPath as NSString).stringByAppendingPathComponent("cmudict-en-us.dict")
            
            if let config = Config(args: ("-hmm", hmm), ("-lm", lm), ("-dict", dict)) {
                
                config.showDebugInfo = false
                
                if let decoder = Decoder(config:config) {
                    decoder.startDecodingSpeech { (hyp) -> () in
                        print("Utterance: \(hyp)")
                    }
                    
                    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, Int64(5.0 * Double(NSEC_PER_SEC))) , dispatch_get_main_queue(), { () -> Void in
                       // decoder.stopDecodingSpeech()
                    })
                    
                }
                
            } else {
            }
            
        } else {
        }
```

**Comment by BrunoBerisso** [comment]
Hi.

I just update the implementation for `startDecodingSpeech` and it's working in OSX. This implementation use `AVAudioEngine` like the PR I mention before. Try checkout the branch _audioengine_streaming_ with carthage and give ti a try. The line in your Cartflie should be like:

```
github "Tryolabs/TLSphinx" == "audioengine_streaming"
```

Another reason for your issue is that the utterances are reported when they are detected. This means that you have to test in a silent environment so Sphinx can detect when an utterance start and end. If Sphinx don't detect any silence it never report anything.

Hope this new implementation work better than the old one. Let us know.

**Comment by BrunoBerisso** [comment]
Hey, just merge this to `main` so just run an update to get the last version. I will close this issue now, If you find another problem let me know.
