### ISSUE TITLE
Swift 3.0

### ISSUE THREAD

**Issue by ss-pq** [tryolabs/TLSphinx#25]
Hello tyolabs! 

Is there any swift 3.0 refactor? 

SS

**Comment by BrunoBerisso** [comment]
Hi!

Not yet, I'm on vacations until next week. Maybe I have some time to play with Swift 3 and update TLSphinx then.

Will post any update on this thread.

Thanks for asking!

**Comment by ss-pq** [comment]
Happy vacations. 
Was going to refactor to 3.0 and post it, where the refactor seems to be quite simple, but I am stuck with the following in config:

Config.swift:25:72: Cannot convert value of type '[UnsafeMutablePointer<Int8>]' to expected argument type 'UnsafeMutablePointer<Int8>?'

throwing here:
 // Create [UnsafeMutablePointer<Int8>].
        cArgs = args.flatMap { (name, value) -> [UnsafeMutablePointer<Int8>] in
            //strdup move the strings to the heap and return a UnsageMutablePointer<Int8>
            return [strdup(name),strdup(value)]
        }
        
        // &cArgs here throws the error, which has got me stuck. *************************
        cmdLnConf = cmd_ln_parse_r(nil, ps_args(), CInt(cArgs.count), &cArgs, STrue)
        // *************************
        

if cmdLnConf == nil {
            return nil
        }


If we find a solution, then a swift 3.0 version can be ready for after vacation both for mac and iOS
: )

**Comment by ss-pq** [comment]
an incentive, and update on the wrappers functionality as a suggestion, which works for 2.3
Which is much faster and more stable

https://github.com/ss-pq/SSPhinx/tree/UpdatedLib

**Comment by ss-pq** [comment]
When can an 3.0 be expected?

**Comment by BrunoBerisso** [comment]
I can't really tell :(

Right now we are working with a big company and don't have much time to spend on TLSphinx. As you may noted I already mark other issues with a _help wanted_ sign to try to address people to contribute.

I will do the same with this one, maybe we can attract some more people to help us. Thanks for push this issue!

**Comment by ss-pq** [comment]
uhm... perhaps you could meanwhile test the posted branch, as it is much more stable solution, where it runs quite stable memory wise. 
Would you be able to imagine a way to solve the posted obstacle in the refactor? Then perhaps we can have it solved ready for x8? : )

**Comment by cgamache** [comment]
I have a potential Swift 3.0 conversion. On the plus side, all tests pass, and it outputs utterances in the simulator. 

On the minus side, it fails the same way that the Swift 2.1 version does on my iPhone 6s. I can't get either one to work correctly.

I can make a pull request if someone with more expertise can verify the conversion. LMK.

**Comment by ss-pq** [comment]
Hi. 
Uhm... is there anything I can help with in regards of the crashes to get things moving, as such updates would be great. Is it running on the new Sphinx version?

**Comment by cgamache** [comment]
Pull request created. If you want to try it out you should be able to fork my clone of the repo. My forked repo's branch is swift-3.0.

This is a merge to master, so it is running on whichever Sphinx version that is tied to. If that's not the most recent, point me in the direction of where it needs to go.

I'd be interested to see if it works for you...

**Comment by BrunoBerisso** [comment]
@cgamache thank you so much for your pull request! Do you do it manually or with the Xcode assistant?

I believe that @ss-pq is talking about it CMUShpinx, the engine that TLSphinx is wrapping. The new version is _5prealpha_ (despinte the name it's the recommended one). I create a new issue for the CMUSphinx update here #28

**Comment by ss-pq** [comment]
@cgamache Forked, gonna look into it.

**Comment by cgamache** [comment]
@BrunoBerisso I started with XCode assistant, and where XCode assistant had trouble I stepped in to fix the the issues or mistranslations. The major trouble spots were with GCD and with the UnsafeMutablePointer values. 

One side note... I made another patch when I found that psDecoder would sometimes be nil in Decoder.swift when `fileprivate func get_hyp() -> Hypothesis?`  would be called 

https://github.com/cgamache/TLSphinx/commit/a89a4c974e2293d3a382d274fe79e46cdb020a22

I ended up just returning nil if psDecoder was nil coming in. I surmised that it was probably a harmless side effect of the multi-threading. You may want to take a peek at that to see if that matches the original intent.

**Comment by ss-pq** [comment]
@cgamache been doing some testing and have found a stable solution for the memory crashes. 
+= 1 on #28 for solutions.

**Comment by BrunoBerisso** [comment]
Merged the PR #27 from @cgamache !
Now we have a Swift 3 version in the develop branch :)

Thank you very much Chris!
