### ISSUE TITLE
Grammar?

### ISSUE THREAD

**Issue by qwill** [tryolabs/TLSphinx#26]
Does this port of TLSphinx have GRAMMAR capabilities? I don't want the entire dictionary I just want about 3 specific words.

**Comment by BrunoBerisso** [comment]
You can always construct a [custom dictionary](http://cmusphinx.sourceforge.net/wiki/tutorialdict) really easy and also a [custom language model](http://cmusphinx.sourceforge.net/wiki/tutoriallm) not that easy.

There is a ObjC librar [OpenEars](http://www.politepix.com/) that let you do just what you want really easy and work great.

It would be great to have this capabilities in TLSphinx for sure!
