### ISSUE TITLE
Update CMUSphinx to last version

### ISSUE THREAD

**Issue by BrunoBerisso** [tryolabs/TLSphinx#28]
The CMUSphinx engine used by TLSphinx is out of date. A new version is available here: http://cmusphinx.sourceforge.net/wiki/download

We need to:
- get a brief of the changes
- update the version used here
- take the chance to polish the engine update process (add scripts to generate the lib from the source to the repo)

**Comment by ss-pq** [comment]
+1

**Comment by vhinic** [comment]
+1

**Comment by ss-pq** [comment]
is there any way to clean debugger log while running?

**Comment by cgamache** [comment]
For the current version, what are TLSphinx/Sphinx/lib/pocketsphinx/libpocketsphinx.a, TLSphinx/Sphinx/lib/sphinxbase/libsphinxad.a , and TLSphinx/Sphinx/lib/sphinxbase/libsphinxbase.a and how do they differ from the platform-specific versions?

**Comment by BrunoBerisso** [comment]
@cgamache They are fat binaries, they contains the compiled versions for: armv7, armv7s, i386, x86_64 and arm64. Try `lipo -info` with that files.

@ss-pq what are you running?

**Comment by cgamache** [comment]
Thanks. That explains my linking issues. I'm trying to work out what to replace library-wise for 5prealpha. Candidly speaking, this is my first dive into integrating a new C library into an XCode project. Heretofore, I've used others' fine work and haven't ever had to think about it.

I suppose this issue as as good a place as any to have a discussion... I can't see where the platform-specific binaries are being referenced by the Sphinx module or the main project. Are they ever put in play or are they there in case someone wants to explicitly co-opt a single platform's library? Is there some sort of convention that the linker uses to pick a library to link against that I'm unaware of?

**Comment by cgamache** [comment]
A quick observation: 

The desire to create an automated library build system for smooth updates is a good one, but a bit ambitious at this point. I had to manually tweak the Sphinx 5prealpha to get it to build under XCode8 which is less than ideal for creating an automated fetch-and-build system for this library. 

Maybe next go-around?

@BrunoBerisso asked for a PR against master without Swift-3.0. Happy to oblige!

**Comment by BrunoBerisso** [comment]
Hey @cgamache!

Thank you very much for this 😄 I will try your PR and merge it as soon as I get to my machine.

About the engine update process I wasn't clear in my description. What I meant was upload the build script used to generate the fat binaries and maybe add some documentation to ghe README that explains a little how to procede so it's more clear how TLSphinx work.

I totally agree with you that make it full automatic isn't posible at this point.

Do you use [this](https://github.com/cmusphinx/pocketsphinx-ios-demo/blob/master/build_iphone.sh) script to build the binaries?

Thanks!

**Comment by BrunoBerisso** [comment]
PR #30 is merged.
