### ISSUE TITLE
Playground support

### ISSUE THREAD

**Issue by DanielAsher** [tryolabs/TLSphinx#3]
Great framework!

I tried using it in a playground, but received this error:
```
Playground execution failed: <module-includes>:1:9: note: in file included from <module-includes>:1:
#import "/Users/Daniel/Library/Developer/Xcode/DerivedData/TLSphinx-erkapyujijryxefqxdotszzkybyx/Build/Products/Debug-iphonesimulator/TLSphinx.framework/Headers/TLSphinx.h"
        ^
/Users/Daniel/Library/Developer/Xcode/DerivedData/TLSphinx-erkapyujijryxefqxdotszzkybyx/Build/Products/Debug-iphonesimulator/TLSphinx.framework/Headers/TLSphinx.h:20:9: error: module 'Sphinx' not found
@import Sphinx;
        ^
could not build Objective-C module 'TLSphinx'A fatal parse error has occurred.  LLDB may become unstable; please restart your debug session as soon as possible.
```

I'm not sure if this is something to do with the linked static libraries.

**Comment by BrunoBerisso** [comment]
Hi Daniel.

Thanks! :) Glad you like it!

Do you have a project for your playground or just a playground? How do you get TLSphinx? (fork, clone, Carthage, etc).

You are right, the error says: `error: module 'Sphinx' not found` The Sphinx module is the core static library. I think you need to have your playground as part of an XCode project to tell your playground where to find third party frameworks, check [this link](http://stackoverflow.com/questions/24046160/how-to-i-import-3rd-party-frameworks-into-xcode-playground).

Please let me know how it goes.

**Comment by BrunoBerisso** [comment]
Close this issue until have some feedback
