### ISSUE TITLE
Return of the Sphinx

### ISSUE THREAD

**Issue by ss-pq** [tryolabs/TLSphinx#31]
Good morning @BrunoBerisso 
Been on vacation and done initial testing with the swift 2.3 first version.
The results are amazing, with a most stable memory handling, which I managed to resolve to result in a full stable versions with streaming API.
How are we doing with 3.0? 
Is there any testing to be conducted?
Kind regards
SS

**Comment by ss-pq** [comment]
Do we have a slack to connect with?

**Comment by cgamache** [comment]
Check the development branch for Swift 3.0 as a work-in-progress. Unit tests pass. It functions in the simulator. I can't get it to run on iOS hardware which uses AVAudioEngine. My next experiment involves injecting a mixer node in between the input node and the output node to alleviate problems with bitrate mismatch when running on hardware. I'd love some help ironing that out.

**Comment by ss-pq** [comment]
In the process of iterating, and more than happy to share the solutions, where the current testing has been on desktop.
Do you run on mobile @cgamache ?

**Comment by BrunoBerisso** [comment]
Hey! I create a slack team https://tlsphinx.slack.com so we can discuss things without creating issues :)

**Comment by cgamache** [comment]
@ss-pq ... Yes. I am attempting to run on mobile.

**Comment by cgamache** [comment]
@BrunoBerisso ... having trouble signing up for the slack team... 

> This team's administrator has not enabled email signups.
> Ask your administrator to send you an invitation.

**Comment by BrunoBerisso** [comment]
@cgamache I send you an invite by email. I'm on trying to put a _"join us on slack"_ button to the README so we make this process simpler.

**Comment by BrunoBerisso** [comment]
Done. We have a Slack button on the [README](https://github.com/tryolabs/TLSphinx/blob/master/README.md) :)

Close this issue, see you there!
