### ISSUE TITLE
when I converted the project to swift3,I got this error please help me

### ISSUE THREAD

**Issue by sarsbug** [tryolabs/TLSphinx#35]
`public init?(args: (String,String)...) {
        
        // Create [UnsafeMutablePointer<Int8>].
        cArgs = args.flatMap { (name, value) -> [UnsafeMutablePointer<Int8>] in
            //strdup move the strings to the heap and return a UnsageMutablePointer<Int8>
            return [strdup(name),strdup(value)]
        }
        
        //var copycArgs: UnsafeMutablePointer<Int8> = cArgs[0]
        cmdLnConf = cmd_ln_parse_r(nil, ps_args(), CInt(cArgs.count), &cArgs, STrue)
        
        if cmdLnConf == nil {
            return nil
        }
    }`

TLSphinx/TLSphinx/Config.swift:26:72: Cannot convert value of type '[UnsafeMutablePointer<Int8>]' to expected argument type 'UnsafeMutablePointer<Int8>?'

**Comment by BrunoBerisso** [comment]
Hi!

Thanks for call my attention to this! This project was already migrated to swift 3 but I forget to publish a release. [Here is a beta for the v1.0](https://github.com/tryolabs/TLSphinx/releases/tag/1.0.0-beta.1) that includes, among some other things, the migration to swift 3.

I really apreciaste your interest and let me know if this work for you.

Thanks

**Comment by sarsbug** [comment]
It worked well thank you very much
