### ISSUE TITLE
Enable bitcode support

### ISSUE THREAD

**Issue by coredumped** [tryolabs/TLSphinx#36]
I wonder if you're building sphinxbase/pocketsphinx on your own or with the `build_iphone.sh` script provided by pocketsphinx-ios-demo? I just PR'd them with the _smallest change ever_ just to enable bitcode (eg. -embed-bitcode). 
Would you consider updating your scripts and thus enabling bitcode support form TLSphinx as well?

**Comment by BrunoBerisso** [comment]
I use a slightly modified version of that script that also build the fat binary. I just realice that they being making some changes to that script so, yes. We should update our version of the TLSphinx engine.

I will try to get into this sooner rather than latter, If you want to tackle this PRs are more than welcome :)

Thanks for the advice!

**Comment by coredumped** [comment]
If you hand me your build script or better yet include it in your repo I can take a look at it and try to make it work, hopefully what needs to be changed is not much either.

**Comment by BrunoBerisso** [comment]
I'm looking at the current version of [build_iphone.sh](https://github.com/cmusphinx/pocketsphinx-ios-demo/blob/master/build_iphone.sh) and the only change I think is still needed in the oficial version is pass `--with-sphinxbase="$SPHINXBASE_DIR/$ARCH"` with the right path at `SPHINXBASE_DIR` when compiling Pocketsphinx.

Attached are the scripts I use when first upload the project. Keep in mind that we merge #30 that update the engine so the build scripts used there may be different. I don't think we have anything significant, @cgamache something to say?

Also, if you are planning to do this be aware of get the last version of the CMUSphinx code and include the .h in your PR :)

Thanks!

[ios-build-scripts.zip](https://github.com/tryolabs/TLSphinx/files/1045705/ios-build-scripts.zip)

**Comment by coredumped** [comment]
Will do my best!
