### ISSUE TITLE
I've tried the 1.0.0-beta.1 version,but I can't get any recognition.

### ISSUE THREAD

**Issue by sarsbug** [tryolabs/TLSphinx#38]
I tried it on simulator and my phone but I can't get any recognition.
the hasSpeech is aways false

```swift
let hasSpeech = in_speech()

switch (speechState) {
case .silence where hasSpeech:
    speechState = .speech
case .speech where !hasSpeech:
    speechState = .utterance
case .utterance where !hasSpeech:
    speechState = .silence
default:
    break
}
```

<details>
    <summary>this is the log</summary>
<p>

Process: 2048 frames - 4096 bytes - sample time: 46622
Process: 2048 frames - 4096 bytes - sample time: 48670
Process: 2048 frames - 4096 bytes - sample time: 50718
Process: 2048 frames - 4096 bytes - sample time: 52766
Process: 2048 frames - 4096 bytes - sample time: 54814
Process: 2048 frames - 4096 bytes - sample time: 56862
Process: 2048 frames - 4096 bytes - sample time: 58910
Process: 2048 frames - 4096 bytes - sample time: 60958
Process: 2048 frames - 4096 bytes - sample time: 63006
Process: 2048 frames - 4096 bytes - sample time: 65054
Process: 2048 frames - 4096 bytes - sample time: 67102
Process: 2048 frames - 4096 bytes - sample time: 69150
Process: 2048 frames - 4096 bytes - sample time: 71198
Process: 2048 frames - 4096 bytes - sample time: 73246
Process: 2048 frames - 4096 bytes - sample time: 75294
Process: 2048 frames - 4096 bytes - sample time: 77342
Process: 2048 frames - 4096 bytes - sample time: 79390
Process: 2048 frames - 4096 bytes - sample time: 81438
Process: 2048 frames - 4096 bytes - sample time: 83486
Process: 2048 frames - 4096 bytes - sample time: 85534
Process: 2048 frames - 4096 bytes - sample time: 87582
Process: 2048 frames - 4096 bytes - sample time: 89630
Process: 2048 frames - 4096 bytes - sample time: 91678
Process: 2048 frames - 4096 bytes - sample time: 93726
Process: 2048 frames - 4096 bytes - sample time: 95774
Process: 2048 frames - 4096 bytes - sample time: 97822
Process: 2048 frames - 4096 bytes - sample time: 99870
Process: 2048 frames - 4096 bytes - sample time: 101918
Process: 2048 frames - 4096 bytes - sample time: 103966
Process: 2048 frames - 4096 bytes - sample time: 106014
Process: 2048 frames - 4096 bytes - sample time: 108062
Process: 2048 frames - 4096 bytes - sample time: 110110
Process: 2048 frames - 4096 bytes - sample time: 112158
Process: 2048 frames - 4096 bytes - sample time: 114206
Process: 2048 frames - 4096 bytes - sample time: 116254
Process: 2048 frames - 4096 bytes - sample time: 118302
Process: 2048 frames - 4096 bytes - sample time: 120350
Process: 2048 frames - 4096 bytes - sample time: 122398
Process: 2048 frames - 4096 bytes - sample time: 124446
Process: 2048 frames - 4096 bytes - sample time: 126494
Process: 2048 frames - 4096 bytes - sample time: 128542
Process: 2048 frames - 4096 bytes - sample time: 130590
Process: 2048 frames - 4096 bytes - sample time: 132638
Process: 2048 frames - 4096 bytes - sample time: 134686
Process: 2048 frames - 4096 bytes - sample time: 136734
Process: 2048 frames - 4096 bytes - sample time: 138782
Process: 2048 frames - 4096 bytes - sample time: 140830
Process: 2048 frames - 4096 bytes - sample time: 142878
Process: 2048 frames - 4096 bytes - sample time: 144926
Process: 2048 frames - 4096 bytes - sample time: 146974
Process: 2048 frames - 4096 bytes - sample time: 149022
Process: 2048 frames - 4096 bytes - sample time: 151070
Process: 2048 frames - 4096 bytes - sample time: 153118
Process: 2048 frames - 4096 bytes - sample time: 155166
Process: 2048 frames - 4096 bytes - sample time: 157214
Process: 2048 frames - 4096 bytes - sample time: 159262
Process: 2048 frames - 4096 bytes - sample time: 161310
Process: 2048 frames - 4096 bytes - sample time: 163358
Process: 2048 frames - 4096 bytes - sample time: 165406
Process: 2048 frames - 4096 bytes - sample time: 167454
Process: 2048 frames - 4096 bytes - sample time: 169502
Process: 2048 frames - 4096 bytes - sample time: 171550
Process: 2048 frames - 4096 bytes - sample time: 173598
Process: 2048 frames - 4096 bytes - sample time: 175646
Process: 2048 frames - 4096 bytes - sample time: 177694
Process: 2048 frames - 4096 bytes - sample time: 179742
Process: 2048 frames - 4096 bytes - sample time: 181790
Process: 2048 frames - 4096 bytes - sample time: 183838
Process: 2048 frames - 4096 bytes - sample time: 185886
Process: 2048 frames - 4096 bytes - sample time: 187934
Process: 2048 frames - 4096 bytes - sample time: 189982
Process: 2048 frames - 4096 bytes - sample time: 192030
Process: 2048 frames - 4096 bytes - sample time: 194078
Process: 2048 frames - 4096 bytes - sample time: 196126
Process: 2048 frames - 4096 bytes - sample time: 198174
Process: 2048 frames - 4096 bytes - sample time: 200222
Process: 2048 frames - 4096 bytes - sample time: 202270
Process: 2048 frames - 4096 bytes - sample time: 204318
Process: 2048 frames - 4096 bytes - sample time: 206366
Process: 2048 frames - 4096 bytes - sample time: 208414
Process: 2048 frames - 4096 bytes - sample time: 210462
Process: 2048 frames - 4096 bytes - sample time: 212510
Process: 2048 frames - 4096 bytes - sample time: 214558
Process: 2048 frames - 4096 bytes - sample time: 216606
Process: 2048 frames - 4096 bytes - sample time: 218654
Process: 2048 frames - 4096 bytes - sample time: 220702
Process: 2048 frames - 4096 bytes - sample time: 222750
Process: 2048 frames - 4096 bytes - sample time: 224798
Process: 2048 frames - 4096 bytes - sample time: 226846
Process: 2048 frames - 4096 bytes - sample time: 228894
Process: 2048 frames - 4096 bytes - sample time: 230942
Process: 2048 frames - 4096 bytes - sample time: 232990
Process: 2048 frames - 4096 bytes - sample time: 235038
Process: 2048 frames - 4096 bytes - sample time: 237086
Process: 2048 frames - 4096 bytes - sample time: 239134
Process: 2048 frames - 4096 bytes - sample time: 241182
Process: 2048 frames - 4096 bytes - sample time: 243230
Process: 2048 frames - 4096 bytes - sample time: 245278
Process: 2048 frames - 4096 bytes - sample time: 247326
Process: 2048 frames - 4096 bytes - sample time: 249374
Process: 2048 frames - 4096 bytes - sample time: 251422
Process: 2048 frames - 4096 bytes - sample time: 253470
Process: 2048 frames - 4096 bytes - sample time: 255518
Process: 2048 frames - 4096 bytes - sample time: 257566
Process: 2048 frames - 4096 bytes - sample time: 259614
Process: 2048 frames - 4096 bytes - sample time: 261662
Process: 2048 frames - 4096 bytes - sample time: 263710
Process: 2048 frames - 4096 bytes - sample time: 265758
Process: 2048 frames - 4096 bytes - sample time: 267806
Process: 2048 frames - 4096 bytes - sample time: 269854
Process: 2048 frames - 4096 bytes - sample time: 271902
Process: 2048 frames - 4096 bytes - sample time: 273950
Process: 2048 frames - 4096 bytes - sample time: 275998
Process: 2048 frames - 4096 bytes - sample time: 278046
Process: 2048 frames - 4096 bytes - sample time: 280094
Process: 2048 frames - 4096 bytes - sample time: 282142
Process: 2048 frames - 4096 bytes - sample time: 284190
Process: 2048 frames - 4096 bytes - sample time: 286238
Process: 2048 frames - 4096 bytes - sample time: 288286
Process: 2048 frames - 4096 bytes - sample time: 290334
Process: 2048 frames - 4096 bytes - sample time: 292382
Process: 2048 frames - 4096 bytes - sample time: 294430
Process: 2048 frames - 4096 bytes - sample time: 296478
Process: 2048 frames - 4096 bytes - sample time: 298526
Process: 2048 frames - 4096 bytes - sample time: 300574
Process: 2048 frames - 4096 bytes - sample time: 302622
Process: 2048 frames - 4096 bytes - sample time: 304670
Process: 2048 frames - 4096 bytes - sample time: 306718
Process: 2048 frames - 4096 bytes - sample time: 308766
Process: 2048 frames - 4096 bytes - sample time: 310814
Process: 2048 frames - 4096 bytes - sample time: 312862
Process: 2048 frames - 4096 bytes - sample time: 314910
Process: 2048 frames - 4096 bytes - sample time: 316958
Process: 2048 frames - 4096 bytes - sample time: 319006
Process: 2048 frames - 4096 bytes - sample time: 321054
Process: 2048 frames - 4096 bytes - sample time: 323102
Process: 2048 frames - 4096 bytes - sample time: 325150
Process: 2048 frames - 4096 bytes - sample time: 327198
Process: 2048 frames - 4096 bytes - sample time: 329246
Process: 2048 frames - 4096 bytes - sample time: 331294
Process: 2048 frames - 4096 bytes - sample time: 333342
Process: 2048 frames - 4096 bytes - sample time: 335390
Process: 2048 frames - 4096 bytes - sample time: 337438
Process: 2048 frames - 4096 bytes - sample time: 339486
Process: 2048 frames - 4096 bytes - sample time: 341534
Process: 2048 frames - 4096 bytes - sample time: 343582
Process: 2048 frames - 4096 bytes - sample time: 345630
Process: 2048 frames - 4096 bytes - sample time: 347678
Process: 2048 frames - 4096 bytes - sample time: 349726
Process: 2048 frames - 4096 bytes - sample time: 351774
Process: 2048 frames - 4096 bytes - sample time: 353822
Process: 2048 frames - 4096 bytes - sample time: 355870
Process: 2048 frames - 4096 bytes - sample time: 357918
Process: 2048 frames - 4096 bytes - sample time: 359966
Process: 2048 frames - 4096 bytes - sample time: 362014
Process: 2048 frames - 4096 bytes - sample time: 364062
Process: 2048 frames - 4096 bytes - sample time: 366110
Process: 2048 frames - 4096 bytes - sample time: 368158
Process: 2048 frames - 4096 bytes - sample time: 370206
Process: 2048 frames - 4096 bytes - sample time: 372254
Process: 2048 frames - 4096 bytes - sample time: 374302
Process: 2048 frames - 4096 bytes - sample time: 376350
Process: 2048 frames - 4096 bytes - sample time: 378398
Process: 2048 frames - 4096 bytes - sample time: 380446
Process: 2048 frames - 4096 bytes - sample time: 382494
Process: 2048 frames - 4096 bytes - sample time: 384542
Process: 2048 frames - 4096 bytes - sample time: 386590
Process: 2048 frames - 4096 bytes - sample time: 388638
Process: 2048 frames - 4096 bytes - sample time: 390686
Process: 2048 frames - 4096 bytes - sample time: 392734
Process: 2048 frames - 4096 bytes - sample time: 394782
Process: 2048 frames - 4096 bytes - sample time: 396830
Process: 2048 frames - 4096 bytes - sample time: 398878
Process: 2048 frames - 4096 bytes - sample time: 400926
Process: 2048 frames - 4096 bytes - sample time: 402974
Process: 2048 frames - 4096 bytes - sample time: 405022
Process: 2048 frames - 4096 bytes - sample time: 407070
Process: 2048 frames - 4096 bytes - sample time: 409118
Process: 2048 frames - 4096 bytes - sample time: 411166
Process: 2048 frames - 4096 bytes - sample time: 413214
Process: 2048 frames - 4096 bytes - sample time: 415262
Process: 2048 frames - 4096 bytes - sample time: 417310
Process: 2048 frames - 4096 bytes - sample time: 419358
Process: 2048 frames - 4096 bytes - sample time: 421406
Process: 2048 frames - 4096 bytes - sample time: 423454
Process: 2048 frames - 4096 bytes - sample time: 425502
Process: 2048 frames - 4096 bytes - sample time: 427550
Process: 2048 frames - 4096 bytes - sample time: 429598
Process: 2048 frames - 4096 bytes - sample time: 431646
Process: 2048 frames - 4096 bytes - sample time: 433694
Process: 2048 frames - 4096 bytes - sample time: 435742
Process: 2048 frames - 4096 bytes - sample time: 437790
Process: 2048 frames - 4096 bytes - sample time: 439838
Process: 2048 frames - 4096 bytes - sample time: 441886
Process: 2048 frames - 4096 bytes - sample time: 443934
Process: 2048 frames - 4096 bytes - sample time: 445982
Process: 2048 frames - 4096 bytes - sample time: 448030
Process: 2048 frames - 4096 bytes - sample time: 450078
Process: 2048 frames - 4096 bytes - sample time: 452126
Process: 2048 frames - 4096 bytes - sample time: 454174
Process: 2048 frames - 4096 bytes - sample time: 456222
Process: 2048 frames - 4096 bytes - sample time: 458270
Process: 2048 frames - 4096 bytes - sample time: 460318
Process: 2048 frames - 4096 bytes - sample time: 462366
Process: 2048 frames - 4096 bytes - sample time: 464414
Process: 2048 frames - 4096 bytes - sample time: 466462
Process: 2048 frames - 4096 bytes - sample time: 468510
Process: 2048 frames - 4096 bytes - sample time: 470558
Process: 2048 frames - 4096 bytes - sample time: 472606
Process: 2048 frames - 4096 bytes - sample time: 474654
Process: 2048 frames - 4096 bytes - sample time: 476702
Process: 2048 frames - 4096 bytes - sample time: 478750
Process: 2048 frames - 4096 bytes - sample time: 480798
Process: 2048 frames - 4096 bytes - sample time: 482846
Process: 2048 frames - 4096 bytes - sample time: 484894
Process: 2048 frames - 4096 bytes - sample time: 486942
Process: 2048 frames - 4096 bytes - sample time: 488990
Process: 2048 frames - 4096 bytes - sample time: 491038
Process: 2048 frames - 4096 bytes - sample time: 493086
Process: 2048 frames - 4096 bytes - sample time: 495134
Process: 2048 frames - 4096 bytes - sample time: 497182
Process: 2048 frames - 4096 bytes - sample time: 499230
Process: 2048 frames - 4096 bytes - sample time: 501278
Process: 2048 frames - 4096 bytes - sample time: 503326
Process: 2048 frames - 4096 bytes - sample time: 505374
Process: 2048 frames - 4096 bytes - sample time: 507422
Process: 2048 frames - 4096 bytes - sample time: 509470
Process: 2048 frames - 4096 bytes - sample time: 511518
Process: 2048 frames - 4096 bytes - sample time: 513566
Process: 2048 frames - 4096 bytes - sample time: 515614
Process: 2048 frames - 4096 bytes - sample time: 517662
Process: 2048 frames - 4096 bytes - sample time: 519710
Process: 2048 frames - 4096 bytes - sample time: 521758
Process: 2048 frames - 4096 bytes - sample time: 523806
Process: 2048 frames - 4096 bytes - sample time: 525854
Process: 2048 frames - 4096 bytes - sample time: 527902
Process: 2048 frames - 4096 bytes - sample time: 529950
Process: 2048 frames - 4096 bytes - sample time: 531998
Process: 2048 frames - 4096 bytes - sample time: 534046
Process: 2048 frames - 4096 bytes - sample time: 536094
Process: 2048 frames - 4096 bytes - sample time: 538142
Process: 2048 frames - 4096 bytes - sample time: 540190
Process: 2048 frames - 4096 bytes - sample time: 542238
Process: 2048 frames - 4096 bytes - sample time: 544286
Process: 2048 frames - 4096 bytes - sample time: 546334
Process: 2048 frames - 4096 bytes - sample time: 548382
Process: 2048 frames - 4096 bytes - sample time: 550430
Process: 2048 frames - 4096 bytes - sample time: 552478
Process: 2048 frames - 4096 bytes - sample time: 554526
Process: 2048 frames - 4096 bytes - sample time: 556574
Process: 2048 frames - 4096 bytes - sample time: 558622
Process: 2048 frames - 4096 bytes - sample time: 560670
Process: 2048 frames - 4096 bytes - sample time: 562718
Process: 2048 frames - 4096 bytes - sample time: 564766
Process: 2048 frames - 4096 bytes - sample time: 566814
Process: 2048 frames - 4096 bytes - sample time: 568862
Process: 2048 frames - 4096 bytes - sample time: 570910
Process: 2048 frames - 4096 bytes - sample time: 572958
Process: 2048 frames - 4096 bytes - sample time: 575006
Process: 2048 frames - 4096 bytes - sample time: 577054
Process: 2048 frames - 4096 bytes - sample time: 579102
Process: 2048 frames - 4096 bytes - sample time: 581150
Process: 2048 frames - 4096 bytes - sample time: 583198
Process: 2048 frames - 4096 bytes - sample time: 585246
Process: 2048 frames - 4096 bytes - sample time: 587294
Process: 2048 frames - 4096 bytes - sample time: 589342
Process: 2048 frames - 4096 bytes - sample time: 591390
Process: 2048 frames - 4096 bytes - sample time: 593438
Process: 2048 frames - 4096 bytes - sample time: 595486
Process: 2048 frames - 4096 bytes - sample time: 597534
Process: 2048 frames - 4096 bytes - sample time: 599582
Process: 2048 frames - 4096 bytes - sample time: 601630
Process: 2048 frames - 4096 bytes - sample time: 603678
Process: 2048 frames - 4096 bytes - sample time: 605726
Process: 2048 frames - 4096 bytes - sample time: 607774
Process: 2048 frames - 4096 bytes - sample time: 609822
Process: 2048 frames - 4096 bytes - sample time: 611870
Process: 2048 frames - 4096 bytes - sample time: 613918
Process: 2048 frames - 4096 bytes - sample time: 615966
Process: 2048 frames - 4096 bytes - sample time: 618014
Process: 2048 frames - 4096 bytes - sample time: 620062
Process: 2048 frames - 4096 bytes - sample time: 622110
Process: 2048 frames - 4096 bytes - sample time: 624158
Process: 2048 frames - 4096 bytes - sample time: 626206
Process: 2048 frames - 4096 bytes - sample time: 628254
Process: 2048 frames - 4096 bytes - sample time: 630302
Process: 2048 frames - 4096 bytes - sample time: 632350
Process: 2048 frames - 4096 bytes - sample time: 634398
Process: 2048 frames - 4096 bytes - sample time: 636446
Process: 2048 frames - 4096 bytes - sample time: 638494
Process: 2048 frames - 4096 bytes - sample time: 640542
Process: 2048 frames - 4096 bytes - sample time: 642590
Process: 2048 frames - 4096 bytes - sample time: 644638
Process: 2048 frames - 4096 bytes - sample time: 646686
Process: 2048 frames - 4096 bytes - sample time: 648734
Process: 2048 frames - 4096 bytes - sample time: 650782
Process: 2048 frames - 4096 bytes - sample time: 652830
Process: 2048 frames - 4096 bytes - sample time: 654878
Process: 2048 frames - 4096 bytes - sample time: 656926
Process: 2048 frames - 4096 bytes - sample time: 658974
Process: 2048 frames - 4096 bytes - sample time: 661022
Process: 2048 frames - 4096 bytes - sample time: 663070
Process: 2048 frames - 4096 bytes - sample time: 665118
Process: 2048 frames - 4096 bytes - sample time: 667166
Process: 2048 frames - 4096 bytes - sample time: 669214
Process: 2048 frames - 4096 bytes - sample time: 671262
Process: 2048 frames - 4096 bytes - sample time: 673310
Process: 2048 frames - 4096 bytes - sample time: 675358
Process: 2048 frames - 4096 bytes - sample time: 677406
Process: 2048 frames - 4096 bytes - sample time: 679454
Process: 2048 frames - 4096 bytes - sample time: 681502
Process: 2048 frames - 4096 bytes - sample time: 683550
Process: 2048 frames - 4096 bytes - sample time: 685598
Process: 2048 frames - 4096 bytes - sample time: 687646
Process: 2048 frames - 4096 bytes - sample time: 689694
Process: 2048 frames - 4096 bytes - sample time: 691742
Process: 2048 frames - 4096 bytes - sample time: 693790
Process: 2048 frames - 4096 bytes - sample time: 695838
Process: 2048 frames - 4096 bytes - sample time: 697886
Process: 2048 frames - 4096 bytes - sample time: 699934
Process: 2048 frames - 4096 bytes - sample time: 701982
Process: 2048 frames - 4096 bytes - sample time: 704030
Process: 2048 frames - 4096 bytes - sample time: 706078
Process: 2048 frames - 4096 bytes - sample time: 708126
Process: 2048 frames - 4096 bytes - sample time: 710174
Process: 2048 frames - 4096 bytes - sample time: 712222
Process: 2048 frames - 4096 bytes - sample time: 714270
Process: 2048 frames - 4096 bytes - sample time: 716318
Process: 2048 frames - 4096 bytes - sample time: 718366
Process: 2048 frames - 4096 bytes - sample time: 720414
Process: 2048 frames - 4096 bytes - sample time: 722462
Process: 2048 frames - 4096 bytes - sample time: 724510
Process: 2048 frames - 4096 bytes - sample time: 726558
Process: 2048 frames - 4096 bytes - sample time: 728606
Process: 2048 frames - 4096 bytes - sample time: 730654
Process: 2048 frames - 4096 bytes - sample time: 732702
Process: 2048 frames - 4096 bytes - sample time: 734750
Process: 2048 frames - 4096 bytes - sample time: 736798
Process: 2048 frames - 4096 bytes - sample time: 738846
Process: 2048 frames - 4096 bytes - sample time: 740894
Process: 2048 frames - 4096 bytes - sample time: 742942
Process: 2048 frames - 4096 bytes - sample time: 744990
Process: 2048 frames - 4096 bytes - sample time: 747038
Process: 2048 frames - 4096 bytes - sample time: 749086
Process: 2048 frames - 4096 bytes - sample time: 751134
Process: 2048 frames - 4096 bytes - sample time: 753182
Process: 2048 frames - 4096 bytes - sample time: 755230
Process: 2048 frames - 4096 bytes - sample time: 757278
Process: 2048 frames - 4096 bytes - sample time: 759326
Process: 2048 frames - 4096 bytes - sample time: 761374
Process: 2048 frames - 4096 bytes - sample time: 763422
Process: 2048 frames - 4096 bytes - sample time: 765470
Process: 2048 frames - 4096 bytes - sample time: 767518
Process: 2048 frames - 4096 bytes - sample time: 769566
Process: 2048 frames - 4096 bytes - sample time: 771614
</p></details>

**Comment by BrunoBerisso** [comment]
Hi @sarsbug. I can reproduce your case with the simulator running the [live decode tests case](https://github.com/tryolabs/TLSphinx/blob/development/TLSphinxTests/LiveDecode.swift#L20), is that what you are doing?

I think the issue is the input format definition used to setup the AVAudioEngine, this is the current biggest problem with TLSphinx but I don't have time to fix it. We should determine on run time the device capabilities and pick the right input format for the running device.

Please, try to reproduce the issue with [last stable release](https://github.com/tryolabs/TLSphinx/releases/tag/0.0.4).

(pd: I take the liberty to tweak your issue formatting)

**Comment by sarsbug** [comment]
ok thank you very much

**Comment by haozes** [comment]
I have the same issue ,how to fix it?

**Comment by Corasonn** [comment]
I changed the sample rate to 44100 in Decoder.swift (works on iPad Air 2).
The recognition isn't very good. I'm not sure if it's due to the potentially incorrect sample rate or that I'm not a native speaker xD But it recognizes anything :)

```
let formatIn = AVAudioFormat(commonFormat: .pcmFormatFloat32, sampleRate: 44100, channels: 1, interleaved: false)!
let formatOut = AVAudioFormat(commonFormat: .pcmFormatInt16, sampleRate: 44100, channels: 1, interleaved: false)!
```
