### ISSUE TITLE
is this library purely for dictionary recognition?

### ISSUE THREAD

**Issue by michaelwarren1106** [tryolabs/TLSphinx#4]
I'm trying to get a speech-to-text feature up and running in a sample app. What i'm looking for is full hypothesis speech-to-text capability, instead of just keyword dictionary matching. Does this library accomplish that? If so, is there any tutorial on how?

**Comment by BrunoBerisso** [comment]
Hi.

I'm assuming you are talking about dictation vs voice commands right? The speech-to-text always gives you an hypothesis of an audio speech represented as text, so there is always a dictionary involved. 

[CMU Sphinx] can handle both cases, dictation and voice commands (as dictation with a small dictionary), so TLSphinx also has this capabilities. You can check the [basic usage tutorial] on how to use Pocketsphinx for a simple explanation. More documentation can be found in the full [Pocketsphinx API].

Also check the TLSphinx [tests cases] for an example of how to use this APIs in Swift.

Hope this is what you ask for :sweat_smile: 

[CMU Sphinx]: http://cmusphinx.sourceforge.net/
[basic usage tutorial]: http://cmusphinx.sourceforge.net/wiki/tutorialpocketsphinx
[Pocketshpinx API]: http://cmusphinx.sourceforge.net/doc/pocketsphinx/
[tests cases]: https://github.com/tryolabs/TLSphinx/tree/master/TLSphinxTests

**Comment by michaelwarren1106** [comment]
Yes, i'm talking about dictation, not voice commands :) Thanks for the help!
