### ISSUE TITLE
lex failed with exit code 1

### ISSUE THREAD

**Issue by veeralbhateja** [tryolabs/TLSphinx#43]
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lex failed with exit code 1

I tried manual integration of Swift 3 code. I have resolved all other bugs but it gives the above error. Can you please let me know how to resolve this?
<img width="1274" alt="screen shot 2017-09-05 at 6 45 05 pm" src="https://user-images.githubusercontent.com/19327129/30062888-6345d82a-926a-11e7-812a-f7d8e453c8d4.png">

**Comment by veeralbhateja** [comment]
Can anyone here please tell me the step by step process for the integration..

**Comment by BrunoBerisso** [comment]
Hi.

Are you using Xcode 9? Because TLSphinx is not yet compatible with it. You could try with the last release [here](https://github.com/tryolabs/TLSphinx/releases/tag/1.0.0-beta.1) that has support for Swift 3 and migrate from there.

What version of Xcode and TLSphinx do you have?

**Comment by veeralbhateja** [comment]
Thanks for the response.

I am using XCode 8.3.3 and TLSphinx-1.0.0-beta.1.

I have tried each method step by step as mentioned in the blogs still there is no success. 
I am still getting the error  "No such module 'Sphinx'".

If even i update the header search path, library search path and Swift Compiler - Search Paths.Still there is no success.

I have been trying this since morning and have read most of the documents and comments online. Please let me know the process for the successful integration.

Thanks in advance.

**Comment by BrunoBerisso** [comment]
🤔.... That's strange. You are using Carthage right? Do you try also do it [manually](https://github.com/tryolabs/TLSphinx#manual)?

**Comment by veeralbhateja** [comment]
I am trying it manually as the beta version was not available with carthrage.

I am sharing a screen shot with you and if required i can also share the project with you i am working on. Let me know the issue with this so that i can proceed further with this.

Also i want to know few points with you before we proceed further.
What i am trying to implement is that user will command what needs to be done with the database such as Delete, update, Insert. the application will be completely handsfree. User just have to command even to scroll. I was initially using sfspeechrecogniser but due to some restrictions with the apple API i thought of using your's API as it has very positive reviews. Let me know if i can implement the same functionality using your speak to text API.

<img width="1280" alt="screen shot 2017-09-05 at 7 32 29 pm" src="https://user-images.githubusercontent.com/19327129/30065193-b2b26610-9271-11e7-92c6-5c867b7e97c4.png">

**Comment by BrunoBerisso** [comment]
> Let me know if i can implement the same functionality using your speak to text API.

Yes. CMUSphinx is the tool to go with that use case scenario. I used it with [OpenEars](https://www.politepix.com/openears/) with great success. TLSphinx is aimed to be _Swift first_ alternative to OpenEars but I have to say that OpenEars is a much mature project and you probably want to consider it. It has a free version that maybe match your needs.

Having say that. I think I know what's the issue. When you drag the project folder to Xcode it automatically try to compile some files as Swift code that are just config files. I have a working project integrated with the code for you to check but it's too heavy to upload here so instead I take some screenshots.

Let me know if it makes more clear.
![screen shot 2017-09-05 at 3 57 56 pm](https://user-images.githubusercontent.com/3342380/30067602-2148d9de-9253-11e7-9e2a-ceafab91ff2c.png)
![screen shot 2017-09-05 at 3 57 47 pm](https://user-images.githubusercontent.com/3342380/30067603-214970f6-9253-11e7-9ad2-2e29cbeac570.png)
![screen shot 2017-09-05 at 3 57 34 pm](https://user-images.githubusercontent.com/3342380/30067605-214e2fec-9253-11e7-93a1-4921ba29d1c0.png)
![screen shot 2017-09-05 at 3 57 20 pm](https://user-images.githubusercontent.com/3342380/30067604-214a5a2a-9253-11e7-83aa-200391b63565.png)

**Comment by veeralbhateja** [comment]
Thanks Bruno,

I will try using OpenEars for now as you suggested and will see if it is what we require.

Thanks for the screenshots they will definitely be very helpful.

Regards,
Veeral Bhateja

**Comment by ppamorim** [comment]
Happening here too, any idea?

**Comment by veeralbhateja** [comment]
Thanks for your Help..

**Comment by veeralbhateja** [comment]
I just installed it manually. Pods was creating the issue..
