### ISSUE TITLE
Building problems XCode 10

### ISSUE THREAD

**Issue by Katharine-Nizhnichenko** [tryolabs/TLSphinx#49]
Hi! I have a problem with building my test project. Maybe you help me with following situation.
I have installed TLSphinx according https://github.com/cmusphinx/TLSphinx instruction, and try to build project in Xcode 10.1 and see endless building process without errors or warnings with significant growth my CPU %  by processes Xcode and XCBBuildService, which results to hang of my system, repeated attempts do not give results.

Thank you

**Comment by BrunoBerisso** [comment]
Hi @Katharine-Nizhnichenko 

Did you use Carthage or go to the manual installation? If you use Carthage try updating the version to 1.0.0, I didn't update the instructions in the README to point to the latest version sorry 🙄.

If that doesn't work try cloning this repo and run the tests locally. I was able to build the project and run the tests without any problem so it should work.

Let me know how it goes.

**Comment by Katharine-Nizhnichenko** [comment]
Hi Bruno! This situation reproduced only when I use Carthage in my test
project. Now I clone your repo and move xcodeProj in my test project,
TLSpxinx target and my test proj target are build successfully, but I have
same build errors when I import TLSpxinx in Test Target classes,  I added
TLSphinx framework in linked frameworks group, reClean and reBuild both
targets but results are same 10 erros about not found .h files.

Please tell me what could be the case. I did not find suitable advice in
the issues

пт, 15 мар. 2019 г. в 12:29, Bruno Berisso <notifications@github.com>:

**Comment by BrunoBerisso** [comment]
Make sure you add the right values to your header and library search paths as described [here](https://github.com/tryolabs/TLSphinx#manual).

If you still have any error please paste it here.

**Comment by Katharine-Nizhnichenko** [comment]
Yes, paths was incorrect) Now building is successful. Thank you!

**Comment by BrunoBerisso** [comment]
No problem 👍🏻
