### ISSUE TITLE
build with carthage failed

### ISSUE THREAD

**Issue by michaelwarren1106** [tryolabs/TLSphinx#5]
I created a cartfile, and tried to update and it fails everytime.

Thread:   <NSThread: 0x7fbce7080da0>{number = 9, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal arm64 /Users/wst237/Desktop/@home/buttah/Carthage/Checkouts/TLSphinx/TLSphinx/Decoder.swift
	CompileSwift normal arm64 /Users/wst237/Desktop/@home/buttah/Carthage/Checkouts/TLSphinx/TLSphinx/Globals.swift
	CompileSwift normal arm64 /Users/wst237/Desktop/@home/buttah/Carthage/Checkouts/TLSphinx/TLSphinx/Hypotesis.swift
	CompileSwift normal arm64 /Users/wst237/Desktop/@home/buttah/Carthage/Checkouts/TLSphinx/TLSphinx/Config.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(5 failures)

my cartfile has:

git "https://github.com/tryolabs/TLSphinx.git"

**Comment by BrunoBerisso** [comment]
Hey!

Sorry for the absurd delay. Do you try with `github "Tryolabs/TLSphinx" ~> 0.0.1` instead of `git "https://github.com/tryolabs/TLSphinx.git"`?

**Comment by michaelwarren1106** [comment]
I've abandoned this project really. I think its beyond me to even get this installed, much less understand how it works and use it in my app. I've tried, with no success, and havent gotten much in the way of help.

If you have an example of a working project, with everything installed, configured, and actually being used in the App UI, that would be awesome, but I'm too much of a beginner with iOS development to do much else I think...

**Comment by BrunoBerisso** [comment]
Totally get it. ASR is a hard topic and TLSphinx it's not easy to integrate / use even if you have experience.

I don't have a public project using TLSphinx other than an [app available in the App Store](https://itunes.apple.com/us/app/tryolabs-mobile-showcase/id984015314?mt=8). Also I think that the project needs to update the Swift syntax to work in XCode 7 so maybe your errors come from there... It's really a almost mechanical procedure but i don't have time now :(
