### ISSUE TITLE
New Version for Xcode 10.2

### ISSUE THREAD

**Issue by randydalrymple** [tryolabs/TLSphinx#53]
Will a new version for Xcode 10.2 be forthcoming?  The Carthage install fails, since TLSphinxTest compiler is set to Swift 3, which the new Xcode does not support.

**Comment by BrunoBerisso** [comment]
Hi @randydalrymple.

I just push a new branch with the settings updated for Xcode 10.2 Try to use this branch on your cartfile and let me know how it goes, I believe you should set something like:
```
github "Tryolabs/TLSphinx" "xcode_10.2"
```

Please keep me posted here if it works or not so I can push a new version.
Thank you very much!

**Comment by randydalrymple** [comment]
Hello Bruno,

Thank you very much for your quick response.  I was able to build TLSphinx from the new cartfile (yea)!

I'm still having trouble integrating the module into my project.  After dragging TLSphinx.framework into Linked Frameworks and Libraries, and after adding the search and import paths, my project still cannot find TLSphinx during the build process.  The error is "Cannot load underlying module for 'TLSphinx'", which occurs at the line "import TLSphinx".  I'm fairly sure this is an error on my part.  However, if you have any suggestions on what to check, I would gladly accept them.

Again, thank you for your help in getting me over this hurdle.

Randy Dalrymple

________________________________

**Comment by randydalrymple** [comment]
Hello Bruno,

I'm not sure whether I should be corresponding with you directly, or posting a new issue on GitHub.  Please advise me on this.

(1) After building the new framework with the test cartfile, and after following the instructions on the GitHub page, I could build my app successfully with the TLSphinx references.  However, when I tried to load the app on a device I received the error:


dyld: Library not loaded: @rpath/TLSphinx.framework/TLSphinx

  Referenced from: /var/containers/Bundle/Application/EA8430DE-09E7-4866-ACF1-01873BE9031A/WebAudio.app/WebAudio

  Reason: image not found

(lldb)


​I verified that the framework was included in the project, and that the search paths were correct:


[cid:a767c470-d943-49ac-b9a2-ecba1e10e672]

Somehow, it appears that Xcode is seeing the header files to build, but not the framework to load at runtime.  As an experiment, I added the actual framework file to Embedded Binaries, and this seemed to work.  However, I don't think that this is the preferred method.

(2)  Is there a preferred method to add the pocketsphinx/model folders to the project?​

Again, thank you for your help.

Randy Dalrymple
​
________________________________

**Comment by BrunoBerisso** [comment]
Hi,

Sorry for the delay. The preferred method to tackle these issues is always the public channels so you get more chances to get help from other people. I'm trying to maintain this project alive and that would not be possible if we hide the interactions 😅 

About your questions:

1 - Carthage requires an extra step when you are integrating a framework. Check [their instructions](https://github.com/Carthage/Carthage#adding-frameworks-to-an-application) for details but basically:
- if you are building a macOS target you need to add the framework to the _Embedded Binaries_ as you did.
- if you are building another target (iOS, tvOS, etc) you need to add a _run script_ phase as described in the link.

I will fix the instructions on the README to include this last step. Sorry for the confusion.

2 - To include models on the final build you need to drag the folder from Finder to the Xcode file tree. On the dialog that appears select _Create folder reference_
![Screenshot 2019-04-18 at 12 49 56](https://user-images.githubusercontent.com/3342380/56359168-a7597a00-61d8-11e9-978d-690ace66290d.png)

The folder should appear with a blue icon like this
![Screenshot 2019-04-18 at 12 49 33](https://user-images.githubusercontent.com/3342380/56359199-c821cf80-61d8-11e9-9e53-12392caedb1d.png)

Then on your code use the folder name to get the path to the root of the model tree. Check the [Basic test case](https://github.com/tryolabs/TLSphinx/blob/master/TLSphinxTests/Basic.swift#L17) for an example.

Let me know how it goes

**Comment by randydalrymple** [comment]
Bruno,

(1) This worked perfectly.  My problem was that this is my first experience using Carthage, and I was treating it like Cocoa Pods.
(2)  I already added the files in this manner and wanted confirmation that this was the correct method.

Thank you.

Randy

________________________________

**Comment by BrunoBerisso** [comment]
Glad it helps.
I'm closing this issue now, feel free to comment again if something related to this come up again.
