### ISSUE TITLE
French Language

### ISSUE THREAD

**Issue by roro95** [tryolabs/TLSphinx#7]
Hi thanks for you gitHub, very helpful. Do you know I could find the different files for the French language  ?
Thanks
Rodolphe

**Comment by roro95** [comment]
I tried to install the framework with carthage. Got the following errors
carthage update
*** Fetching TLSphinx
*** Checking out TLSphinx at “135e5ae92cd8d67e6a66e6b235164589f813267e”
*** xcodebuild output can be found in /var/folders/x2/_m45kh_d1zzgpsxch7vz8h1c0000gn/T/carthage-xcodebuild.2htWvb.log
*** Building scheme “TLSphinx” in TLSphinx.xcodeproj
** BUILD FAILED **

The following build commands failed:
Ld /Users/Rodolphe/Library/Developer/Xcode/DerivedData/TLSphinx-grehmzfuslixfjdjokkhcvntdhqk/Build/Intermediates/TLSphinx.build/Release-iphoneos/TLSphinx.build/Objects-normal/armv7/TLSphinx normal armv7
Ld /Users/Rodolphe/Library/Developer/Xcode/DerivedData/TLSphinx-grehmzfuslixfjdjokkhcvntdhqk/Build/Intermediates/TLSphinx.build/Release-iphoneos/TLSphinx.build/Objects-normal/arm64/TLSphinx normal arm64
(2 failures)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
A shell task failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
Ld /Users/Rodolphe/Library/Developer/Xcode/DerivedData/TLSphinx-grehmzfuslixfjdjokkhcvntdhqk/Build/Intermediates/TLSphinx.build/Release-iphoneos/TLSphinx.build/Objects-normal/armv7/TLSphinx normal armv7
Ld /Users/Rodolphe/Library/Developer/Xcode/DerivedData/TLSphinx-grehmzfuslixfjdjokkhcvntdhqk/Build/Intermediates/TLSphinx.build/Release-iphoneos/TLSphinx.build/Objects-normal/arm64/TLSphinx normal arm64
(2 failures)

Any idea ? Thanks

**Comment by BrunoBerisso** [comment]
TLSphinx use the CMUSphinx C engine to perform the recognition. There are plenty of language supported by this project and you can even build your own [acoustic] (http://cmusphinx.sourceforge.net/wiki/tutorialam) and [language](http://cmusphinx.sourceforge.net/wiki/tutoriallm) models, [adapt](http://cmusphinx.sourceforge.net/wiki/tutorialadapt) the existing ones or use some of the [provided by the project](http://cmusphinx.sourceforge.net/wiki/download#models).

For French there are optimised versions of the language and acoustic models provided. To use this models with TLSphinx you will need to download the [compressed acoustic model](http://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/French/cmusphinx-fr-5.2.tar.gz/download), the [dictionary](http://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/French%20Language%20Model/fr.dict/download) and the [language model] (http://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/French%20Language%20Model/fr.lm.gmp/download).

The acoustic model is a folder with some files, the language model is a binary file and the dictionary is a text file. Place this three items in a new folder and make it available to your app. Then when initialising a decoder pass the the path to this files like so:

```swift

func frenchDecoder() -> Decoder? {

    if let modelPath = "path to the root folder of the french language files" {
            
        let hmm = (modelPath as NSString).stringByAppendingPathComponent("french-ac-model-folder")
        let lm = (modelPath as NSString).stringByAppendingPathComponent("fr.lm.dmp")
        let dict = (modelPath as NSString).stringByAppendingPathComponent("fr.dict")
        
        if let config = Config(args: ("-hmm", hmm), ("-lm", lm), ("-dict", dict)) {
            return Decoder(config:config)
        } else {
            return nil
        }
    } else {
        return nil
    }
}

```

Please let me know if this work. I don't test it myself yet.

**Comment by BrunoBerisso** [comment]
I will asume this topic to be addressed in the previous answer. Any other feedback / issue related should be posted here.
