### ISSUE TITLE
Issue when installing with Carthage

### ISSUE THREAD

**Issue by roro95** [tryolabs/TLSphinx#8]
I tried to install the framework with carthage. Got the following errors
carthage update
*** Fetching TLSphinx
*** Checking out TLSphinx at “135e5ae92cd8d67e6a66e6b235164589f813267e”
*** xcodebuild output can be found in /var/folders/x2/_m45kh_d1zzgpsxch7vz8h1c0000gn/T/carthage-xcodebuild.2htWvb.log
*** Building scheme “TLSphinx” in TLSphinx.xcodeproj
** BUILD FAILED **

The following build commands failed:
Ld /Users/Rodolphe/Library/Developer/Xcode/DerivedData/TLSphinx-grehmzfuslixfjdjokkhcvntdhqk/Build/Intermediates/TLSphinx.build/Release-iphoneos/TLSphinx.build/Objects-normal/armv7/TLSphinx normal armv7
Ld /Users/Rodolphe/Library/Developer/Xcode/DerivedData/TLSphinx-grehmzfuslixfjdjokkhcvntdhqk/Build/Intermediates/TLSphinx.build/Release-iphoneos/TLSphinx.build/Objects-normal/arm64/TLSphinx normal arm64
(2 failures)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
A shell task failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
Ld /Users/Rodolphe/Library/Developer/Xcode/DerivedData/TLSphinx-grehmzfuslixfjdjokkhcvntdhqk/Build/Intermediates/TLSphinx.build/Release-iphoneos/TLSphinx.build/Objects-normal/armv7/TLSphinx normal armv7
Ld /Users/Rodolphe/Library/Developer/Xcode/DerivedData/TLSphinx-grehmzfuslixfjdjokkhcvntdhqk/Build/Intermediates/TLSphinx.build/Release-iphoneos/TLSphinx.build/Objects-normal/arm64/TLSphinx normal arm64
(2 failures)

Any idea ? Thanks

**Comment by BrunoBerisso** [comment]
Hi,

I just push a new release that should fix this issue. Try update your Cartfile to point to the last tag with this line:

```
github "Tryolabs/TLSphinx" ~> 0.0.2
```

And run: `carthage update --platform iOS --verbose` If it fail again copy the output here so we can work it out.

Thanks

**Comment by roro95** [comment]
Great it works ! thanks

**Comment by BrunoBerisso** [comment]
Nice to know. :)
