### ISSUE TITLE
I have an error on xCode  on Decoder.swift

### ISSUE THREAD

**Issue by qlm7523** [tryolabs/TLSphinx#9]
I have some error on Type SpeechStateNum. RawRepresentable protocol gave me an error like this
<img width="260" alt="2016-01-25 4 58 50" src="https://cloud.githubusercontent.com/assets/7984805/12572564/8b5bcf58-c431-11e5-997a-3a879ee13938.png">
how can I fix this error?

**Comment by BrunoBerisso** [comment]
Hi,

That's strange, `SpeechStateEnum` doesn't have a raw value so it has nothing to do with `RawRepresentable`.

Please try fetch the last release with `git pull`, clean the XCode project and try again. Let me know if this work.

Thanks!

**Comment by qlm7523** [comment]
That error occured when i don't use Carthage, so i use carthage now. but i have another error - library load error like this. 

dyld: Library not loaded: @rpath/TLSphinx.framework/TLSphinx
  Referenced from: /Users/kyj/Library/Developer/CoreSimulator/Devices/5F6CB63D-B073-4988-916F-CBFEDEC6B5C9/data/Containers/Bundle/Application/DEA25CC6-C047-404C-AE81-72DEC8196570/FinalTest.app/FinalTest
  Reason: image not found

But I add library search path like "$(SRCROOT)/Carthage/Checkouts/TLSphinx/Sphinx/lib" and header search path like "$(SRCROOT)/Carthage/Checkouts/TLSphinx/Sphinx/include" and import path like "$(SRCROOT)/Carthage/Checkouts/TLSphinx/Sphinx/include" but it don't work now.

how can i do?

**Comment by BrunoBerisso** [comment]
Hmm, that's strange. That should not be needed.

Could you please tell me what kind of project are you working on? I'm mean, it's an iOS only app? or it has an extension for iWatch or apple TV? Are you using Carthage to link another framework?.

Anyway, I'm glad you can fix it :)

Regards
